# Generated by Django 5.0.14 on 2026-07-07 16:24

import accounts.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(db_index=True, max_length=20, unique=True, validators=[accounts.validators.UsernameValidator(), accounts.validators.validate_illegal_usernames], verbose_name='نام کاربری')),
                ('phone', models.CharField(blank=True, db_index=True, max_length=11, null=True, unique=True, validators=[accounts.validators.PhoneNumberValidator()], verbose_name='شماره تماس')),
                ('first_name', models.CharField(max_length=30, verbose_name='نام')),
                ('last_name', models.CharField(max_length=30, verbose_name='نام خانوادگی')),
                ('is_staff', models.BooleanField(default=False, verbose_name='دسترسی ادمین')),
                ('is_active', models.BooleanField(default=True, verbose_name='وضعیت فعالیت')),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ عضویت')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'کاربر',
                'verbose_name_plural': 'کاربران',
            },
        ),
    ]
