# Generated by Django 5.0.14 on 2026-07-08 13:09

import accounts.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='last_name',
        ),
        migrations.AddField(
            model_name='user',
            name='is_verified',
            field=models.BooleanField(default=False, verbose_name='وضعیت احراز هویت'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(db_index=True, default='a', max_length=11, unique=True, validators=[accounts.validators.PhoneNumberValidator()], verbose_name='شماره تماس'),
            preserve_default=False,
        ),
    ]
